yapf --exclude .egg

diff --git a/.github/workflows/pythonpackage.yml b/.github/workflows/pythonpackage.yml
--- a/.github/workflows/pythonpackage.yml
+++ b/.github/workflows/pythonpackage.yml
@@ -24,7 +24,13 @@ jobs:
     - name: Lint with yapf
       run: |
         pip install yapf
-        yapf -dr --style=yapf.ini --exclude=examples/* ./
+        diffs=$(yapf -dr --style=yapf.ini --exclude=examples/* --exclude=.eggs/* ./)
+        if [ -n "$diffs" ]; then	
+          echo "failed yapf"	
+          echo $diffs	
+          exit 1	
+        fi	
+        echo "pass yapf"
     - name: Test with unittest
       run: |
         python -m unittest test
